name: AWS Authentication

on:
  workflow_call:
    inputs:
      role-to-assume:
        description: 'The AWS IAM role to assume'
        required: true
        type: string
      aws-region:
        description: 'The AWS region to use'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'Optional: AWS Access Key ID for fallback'
        required: false
      AWS_SECRET_ACCESS_KEY:
        description: 'Optional: AWS Secret Access Key for fallback'
        required: false

jobs:
  authenticate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 🔐 Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: GitHubActions-Session-${{ github.run_id }}
          aws-region: ${{ inputs.aws-region }}
          # Fallback to access keys if OIDC is not configured
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID || '' }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY || '' }}
